[package]
name = "tibrary-tags"
version = "0.2.1"
edition = "2021"
rust-version = "1.88"

[lib]
name = "_lofty"
crate-type = ["cdylib"]

[dependencies]
lofty = "=0.25.3"
pyo3 = { version = "0.28", features = ["extension-module", "abi3-py312"] }
sha2 = "0.10"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
